name: drlnd
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - async_generator=1.10
  - autopep8=1.6.0
  - backcall=0.2.0
  - blas=1.0
  - certifi=2021.5.30
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.140
  - cuda-documentation=12.0.76
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - freetype=2.12.1
  - importlib_metadata=4.8.1
  - intel-openmp=2022.1.0
  - ipython_genutils=0.2.0
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - lcms2=2.12
  - libcublas=12.0.1.189
  - libcublas-dev=12.0.1.189
  - libcufft=11.0.0.21
  - libcufft-dev=11.0.0.21
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcusolver=11.4.2.57
  - libcusolver-dev=11.4.2.57
  - libcusparse=12.0.0.76
  - libcusparse-dev=12.0.0.76
  - libnpp=12.0.0.30
  - libnpp-dev=12.0.0.30
  - libnvjpeg=12.0.0.28
  - libnvjpeg-dev=12.0.0.28
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.44.2
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nsight-compute=2022.4.0.15
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.4.0
  - packaging=21.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - prometheus_client=0.13.1
  - pycodestyle=2.8.0
  - pycparser=2.21
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytorch=1.10.2
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - traitlets=4.3.3
  - typing_extensions=4.1.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.6
  - zipp=3.6.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - absl-py==1.3.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - astor==0.8.1
      - atomicwrites==1.4.1
      - attrs==22.2.0
      - bleach==1.5.0
      - cffi==1.15.1
      - cloudpickle==2.2.0
      - colorama==0.4.5
      - cycler==0.11.0
      - cython==0.29.32
      - docopt==0.6.2
      - entrypoints==0.4
      - fasteners==0.18
      - gast==0.5.3
      - glfw==2.5.5
      - grpcio==1.11.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - html5lib==0.9999999
      - imageio==2.15.0
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - iniconfig==1.1.1
      - ipykernel==5.5.6
      - ipython==7.16.3
      - ipywidgets==7.7.2
      - jedi==0.17.2
      - jupyter==1.0.0
      - jupyter-console==6.4.3
      - jupyter-core==4.9.2
      - jupyterlab-widgets==1.1.1
      - kiwisolver==1.3.1
      - lockfile==0.12.2
      - markdown==3.3.7
      - matplotlib==3.3.4
      - mujoco-py==2.1.2.14
      - nbclient==0.5.9
      - nest-asyncio==1.5.6
      - notebook==6.4.10
      - numpy==1.19.5
      - opencv-python==4.6.0.66
      - pandas==1.1.5
      - parso==0.7.1
      - pillow==8.4.0
      - pluggy==1.0.0
      - prometheus-client==0.15.0
      - prompt-toolkit==3.0.36
      - protobuf==3.5.2
      - py==1.11.0
      - pyglet==2.0.2.1
      - pygments==2.13.0
      - pyparsing==3.0.9
      - pyrsistent==0.18.0
      - pytest==7.0.1
      - pytz==2022.7
      - pywin32==305
      - pywinpty==1.1.6
      - pyyaml==6.0
      - pyzmq==24.0.1
      - qtconsole==5.2.2
      - qtpy==2.0.1
      - scipy==1.5.4
      - tensorboard==1.7.0
      - tensorflow==1.7.1
      - termcolor==1.1.0
      - terminado==0.12.1
      - testpath==0.6.0
      - tomli==1.2.3
      - unityagents==0.4.0
      - werkzeug==2.0.3
      - widgetsnbextension==3.6.1
